language: python
python:
  - "3.6"
sudo: required
dist: xenial
services:
  - redis-server
  - xvfb
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
before_install:
  - travis_wait 30 ./misc/install_gdal.sh
  - export PATH=$GDALINST/gdal-2.2.3/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-2.2.3/lib:$LD_LIBRARY_PATH
install:
  - npm -g install topojson
  - pip install --upgrade "setuptools>=25.1" pip
  - pip install -r requirements/dev.txt
  - python setup.py install
  - python setup.py build_ext --inplace
before_script:
  - pushd /tmp && wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d ~/bin/ && popd
script:
  - magrit --help
  - py.test tests/test.py -p no:flaky
  - py.test tests/tests_web.py
addons:
  chrome: stable
  apt:
    sources:
      - sourceline: 'ppa:deadsnakes/ppa'
    packages:
      - python3.6
      - libopenblas-base
      - libopenblas-dev
      - gdal-bin
      - libuv1-dev
      - libgdal-dev
      - libproj-dev
      - libspatialindex-dev
      - libfreetype6
      - libfreetype6-dev
      - libv8-3.14-dev
      - libffi-dev
      - redis-server
      - nodejs
      - nodejs-dev
      - libxslt1-dev
      - libxml2
      - libxml2-dev
      - libkml-dev
      - fluxbox
