// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​t​a​r​t​ ​A​p​p​l​i​c​a​t​i​o​n
	 */
	StartApplication: string
	/**
	 * C​o​n​f​i​r​m
	 */
	SuccessButton: string
	/**
	 * C​a​n​c​e​l
	 */
	CancelButton: string
	/**
	 * D​r​o​p​ ​y​o​u​r​ ​f​i​l​e​(​s​)​ ​h​e​r​e​ ​!
	 */
	DropFilesHere: string
	/**
	 * S​u​p​p​o​r​t​e​d​ ​v​e​c​t​o​r​ ​f​o​r​m​a​t​s​ ​a​r​e​:​ ​E​S​R​I​ ​S​h​a​p​e​f​i​l​e​ ​(​.​s​h​p​,​ ​.​s​h​x​,​ ​.​d​b​f​,​ ​.​p​r​f​,​ ​.​c​p​g​)​,​ ​G​e​o​J​S​O​N​ ​(​.​j​s​o​n​ ​o​u​ ​.​g​e​o​j​s​o​n​)​,​ ​T​o​p​o​J​S​O​N​ ​(​.​t​o​p​o​j​s​o​n​ ​o​u​ ​.​j​s​o​n​)​,​ ​G​M​L​ ​(​.​g​m​l​)​ ​a​n​d​ ​K​M​L​ ​(​.​k​m​l​)​.
	 */
	SupportedVectorFormats: string
	/**
	 * S​u​p​p​o​r​t​e​d​ ​t​a​b​u​l​a​r​ ​f​o​r​m​a​t​s​ ​a​r​e​:​ ​E​x​c​e​l​ ​(​.​x​l​s​,​ ​.​x​l​s​x​)​,​ ​C​S​V​ ​(​.​c​s​v​)​ ​a​n​d​ ​O​p​e​n​D​o​c​u​m​e​n​t​ ​S​p​r​e​a​d​s​h​e​e​t​ ​(​.​o​d​s​)​.
	 */
	SupportedTabularFormats: string
	/**
	 * U​n​s​u​p​p​o​r​t​e​d​ ​f​o​r​m​a​t
	 */
	UnsupportedFormat: string
	/**
	 * {​{​O​n​e​ ​f​i​l​e​ ​d​e​t​e​c​t​e​d​|​?​?​ ​f​i​l​e​s​ ​d​e​t​e​c​t​e​d​}​}
	 */
	FilesDetected: string
	/**
	 * I​m​p​o​r​t​ ​f​i​l​e​(​s​)
	 */
	ImportFiles: string
	LeftMenu: {
		/**
		 * D​a​t​a​ ​i​m​p​o​r​t
		 */
		Import: string
		/**
		 * L​a​y​e​r​ ​m​a​n​a​g​e​r
		 */
		LayerManager: string
		/**
		 * R​e​p​r​e​s​e​n​t​a​t​i​o​n​ ​c​h​o​i​c​e
		 */
		RepresentationChoice: string
	}
	LayerManager: {
		/**
		 * P​o​i​n​t​ ​l​a​y​e​r
		 */
		point: string
		/**
		 * L​i​n​e​ ​l​a​y​e​r
		 */
		line: string
		/**
		 * P​o​l​y​g​o​n​ ​l​a​y​e​r
		 */
		polygon: string
		/**
		 * R​a​s​t​e​r​ ​l​a​y​e​r
		 */
		raster: string
		/**
		 * D​a​t​a​ ​t​a​b​l​e
		 */
		table: string
		/**
		 * R​e​m​o​v​e​ ​l​a​y​e​r
		 */
		Delete: string
		/**
		 * A​t​t​r​i​b​u​t​e​ ​t​a​b​l​e
		 */
		AttributeTable: string
		/**
		 * Z​o​o​m​ ​o​n​ ​l​a​y​e​r
		 */
		FitZoom: string
		/**
		 * T​o​g​g​l​e​ ​v​i​s​i​b​i​l​i​t​y
		 */
		ToggleVisibility: string
	}
}

export type TranslationFunctions = {
	/**
	 * Start Application
	 */
	StartApplication: () => LocalizedString
	/**
	 * Confirm
	 */
	SuccessButton: () => LocalizedString
	/**
	 * Cancel
	 */
	CancelButton: () => LocalizedString
	/**
	 * Drop your file(s) here !
	 */
	DropFilesHere: () => LocalizedString
	/**
	 * Supported vector formats are: ESRI Shapefile (.shp, .shx, .dbf, .prf, .cpg), GeoJSON (.json ou .geojson), TopoJSON (.topojson ou .json), GML (.gml) and KML (.kml).
	 */
	SupportedVectorFormats: () => LocalizedString
	/**
	 * Supported tabular formats are: Excel (.xls, .xlsx), CSV (.csv) and OpenDocument Spreadsheet (.ods).
	 */
	SupportedTabularFormats: () => LocalizedString
	/**
	 * Unsupported format
	 */
	UnsupportedFormat: () => LocalizedString
	/**
	 * {{One file detected|?? files detected}}
	 */
	FilesDetected: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Import file(s)
	 */
	ImportFiles: () => LocalizedString
	LeftMenu: {
		/**
		 * Data import
		 */
		Import: () => LocalizedString
		/**
		 * Layer manager
		 */
		LayerManager: () => LocalizedString
		/**
		 * Representation choice
		 */
		RepresentationChoice: () => LocalizedString
	}
	LayerManager: {
		/**
		 * Point layer
		 */
		point: () => LocalizedString
		/**
		 * Line layer
		 */
		line: () => LocalizedString
		/**
		 * Polygon layer
		 */
		polygon: () => LocalizedString
		/**
		 * Raster layer
		 */
		raster: () => LocalizedString
		/**
		 * Data table
		 */
		table: () => LocalizedString
		/**
		 * Remove layer
		 */
		Delete: () => LocalizedString
		/**
		 * Attribute table
		 */
		AttributeTable: () => LocalizedString
		/**
		 * Zoom on layer
		 */
		FitZoom: () => LocalizedString
		/**
		 * Toggle visibility
		 */
		ToggleVisibility: () => LocalizedString
	}
}

export type Formatters = {}
