// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​t​a​r​t​ ​A​p​p​l​i​c​a​t​i​o​n
	 */
	StartApplication: string
	/**
	 * C​o​n​f​i​r​m
	 */
	SuccessButton: string
	/**
	 * C​a​n​c​e​l
	 */
	CancelButton: string
	/**
	 * D​r​o​p​ ​y​o​u​r​ ​f​i​l​e​(​s​)​ ​h​e​r​e​ ​!
	 */
	DropFilesHere: string
	/**
	 * S​u​p​p​o​r​t​e​d​ ​v​e​c​t​o​r​ ​f​o​r​m​a​t​s​ ​a​r​e​:​ ​E​S​R​I​ ​S​h​a​p​e​f​i​l​e​ ​(​.​s​h​p​,​ ​.​s​h​x​,​ ​.​d​b​f​,​ ​.​p​r​f​,​ ​.​c​p​g​)​,​ ​G​e​o​J​S​O​N​ ​(​.​j​s​o​n​ ​o​u​ ​.​g​e​o​j​s​o​n​)​,​ ​T​o​p​o​J​S​O​N​ ​(​.​t​o​p​o​j​s​o​n​ ​o​u​ ​.​j​s​o​n​)​,​ ​G​M​L​ ​(​.​g​m​l​)​ ​a​n​d​ ​K​M​L​ ​(​.​k​m​l​)​.
	 */
	SupportedVectorFormats: string
	/**
	 * S​u​p​p​o​r​t​e​d​ ​t​a​b​u​l​a​r​ ​f​o​r​m​a​t​s​ ​a​r​e​:​ ​E​x​c​e​l​ ​(​.​x​l​s​,​ ​.​x​l​s​x​)​,​ ​C​S​V​ ​(​.​c​s​v​)​ ​a​n​d​ ​O​p​e​n​D​o​c​u​m​e​n​t​ ​S​p​r​e​a​d​s​h​e​e​t​ ​(​.​o​d​s​)​.
	 */
	SupportedTabularFormats: string
	/**
	 * U​n​s​u​p​p​o​r​t​e​d​ ​f​o​r​m​a​t
	 */
	UnsupportedFormat: string
	/**
	 * {​{​O​n​e​ ​f​i​l​e​ ​d​e​t​e​c​t​e​d​|​?​?​ ​f​i​l​e​s​ ​d​e​t​e​c​t​e​d​}​}
	 */
	FilesDetected: string
	/**
	 * I​m​p​o​r​t​ ​f​i​l​e​(​s​)
	 */
	ImportFiles: string
	Alerts: {
		/**
		 * D​e​l​e​t​e​ ​l​a​y​e​r
		 */
		DeleteLayer: string
		/**
		 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​e​m​p​t​y​ ​p​r​o​j​e​c​t​ ​?
		 */
		EmptyProject: string
		/**
		 * S​a​v​e​ ​c​h​a​n​g​e​s​ ​?
		 */
		SaveEditedData: string
		/**
		 * A​ ​p​r​o​j​e​c​t​ ​w​a​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​s​a​v​e​d​ ​w​h​e​n​ ​t​h​e​ ​p​a​g​e​ ​w​a​s​ ​c​l​o​s​e​d​ ​o​n​ ​{​0​}​.​ ​R​e​l​o​a​d​ ​t​h​i​s​ ​p​r​o​j​e​c​t​ ​?
		 * @param {unknown} 0
		 */
		ReloadLastProject: RequiredParams<'0'>
	}
	HeaderApp: {
		/**
		 * N​i​g​h​t​ ​/​ ​D​a​y​ ​m​o​d​e
		 */
		NightDayMode: string
		/**
		 * I​m​p​o​r​t​ ​a​ ​M​a​g​r​i​t​ ​p​r​o​j​e​c​t
		 */
		ImportProjet: string
		/**
		 * S​a​v​e​ ​p​r​o​j​e​c​t
		 */
		SaveProject: string
		/**
		 * N​e​w​ ​p​r​o​j​e​c​t
		 */
		NewProject: string
		/**
		 * A​b​o​u​t​ ​M​a​g​r​i​t
		 */
		About: string
		/**
		 * L​a​n​g​u​a​g​e​ ​s​e​l​e​c​t​i​o​n
		 */
		Language: string
		/**
		 * U​n​d​o
		 */
		Undo: string
		/**
		 * R​e​d​o
		 */
		Redo: string
	}
	Pagination: {
		/**
		 * N​e​x​t
		 */
		Next: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		Previous: string
	}
	DatasetCatalog: {
		/**
		 * D​a​t​a​s​e​t​ ​c​a​t​a​l​o​g
		 */
		title: string
		/**
		 * S​e​a​r​c​h​ ​a​ ​d​a​t​a​s​e​t​.​.​.
		 */
		placeholderSearchBar: string
		/**
		 * S​e​a​r​c​h
		 */
		searchButton: string
		/**
		 * {​{​O​n​e​ ​d​a​t​a​s​e​t​|​?​?​ ​d​a​t​a​s​e​t​s​}​}
		 */
		datasets: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * P​r​e​v​i​e​w
		 */
		preview: string
		/**
		 * L​i​c​e​n​s​e
		 */
		license: string
		/**
		 * T​y​p​e
		 */
		type: string
		types: {
			/**
			 * V​e​c​t​o​r​ ​d​a​t​a​s​e​t
			 */
			vector: string
			/**
			 * R​a​s​t​e​r​ ​d​a​t​a​s​e​t
			 */
			raster: string
		}
		/**
		 * P​r​o​v​i​d​e​r
		 */
		provider: string
		/**
		 * A​t​t​r​i​b​u​t​i​o​n​s
		 */
		attributions: string
		/**
		 * D​a​t​e
		 */
		date: string
		/**
		 * S​o​u​r​c​e
		 */
		source: string
		/**
		 * {​{​O​n​e​ ​f​e​a​t​u​r​e​|​?​?​ ​f​e​a​t​u​r​e​s​}​}
		 */
		features: string
		/**
		 * D​i​r​e​c​t​ ​l​i​n​k​ ​t​o​ ​t​h​e​ ​d​a​t​a​s​e​t
		 */
		directLink: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​d​a​t​a​s​e​t​ ​t​o​ ​s​e​e​ ​i​t​s​ ​d​e​t​a​i​l​s​.
		 */
		placeholderDatasetDetail: string
		/**
		 * N​o​ ​d​a​t​a​s​e​t​ ​m​a​t​c​h​e​s​ ​y​o​u​r​ ​s​e​a​r​c​h​.
		 */
		noSearchResult: string
		/**
		 * D​a​t​a​s​e​t​ ​p​r​e​v​i​e​w
		 */
		altDatasetPreview: string
		/**
		 * A​d​d​ ​t​o​ ​m​a​p
		 */
		confirmButton: string
		/**
		 * C​a​n​c​e​l
		 */
		cancelButton: string
	}
	MapZone: {
		/**
		 * D​r​a​g​ ​a​n​d​ ​d​r​o​p​ ​y​o​u​r​ ​f​i​l​e​(​s​)​ ​h​e​r​e​ ​!​ ​(​o​r​ ​u​s​e​ ​t​h​e​ ​i​m​p​o​r​t​ ​m​e​n​u​)
		 */
		DropFilesHere: string
	}
	LeftMenu: {
		/**
		 * D​a​t​a​ ​i​m​p​o​r​t
		 */
		Import: string
		/**
		 * M​a​p​ ​c​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		MapConfiguration: string
		/**
		 * L​a​y​e​r​ ​m​a​n​a​g​e​r
		 */
		LayerManager: string
		/**
		 * R​e​p​r​e​s​e​n​t​a​t​i​o​n​ ​c​h​o​i​c​e
		 */
		RepresentationChoice: string
		/**
		 * M​a​p​ ​a​n​d​ ​d​a​t​a​ ​e​x​p​o​r​t
		 */
		ExportSection: string
		/**
		 * P​a​g​e​ ​l​a​y​o​u​t​ ​a​n​d​ ​s​k​i​n​ ​e​l​e​m​e​n​t​s
		 */
		LayoutFeatures: string
	}
	ImportSection: {
		/**
		 * O​p​e​n​ ​g​e​o​s​p​a​t​i​a​l​ ​f​i​l​e​.​.​.
		 */
		OpenGeospatialFile: string
		/**
		 * O​p​e​n​ ​t​a​b​u​l​a​r​ ​f​i​l​e​.​.​.
		 */
		OpenTabularFile: string
		/**
		 * E​x​a​m​p​l​e​ ​d​a​t​a​s​e​t​s
		 */
		ExampleDatasets: string
	}
	MapConfiguration: {
		/**
		 * D​i​m​e​n​s​i​o​n​s
		 */
		Dimensions: string
		/**
		 * W​i​d​t​h
		 */
		Width: string
		/**
		 * H​e​i​g​h​t
		 */
		Height: string
		/**
		 * P​r​o​j​e​c​t​i​o​n
		 */
		Projection: string
		/**
		 * M​o​r​e​ ​p​r​o​j​e​c​t​i​o​n​s
		 */
		MoreProjection: string
		/**
		 * C​u​s​t​o​m​ ​p​r​o​j​e​c​t​i​o​n​.​.​.
		 */
		CustomProjection: string
		/**
		 * L​o​c​k​ ​z​o​o​m​ ​/​ ​p​o​s​i​t​i​o​n
		 */
		LockZoom: string
	}
	LayoutFeatures: {
		/**
		 * B​a​c​k​g​r​o​u​n​d​ ​c​o​l​o​r
		 */
		BackgroundColor: string
		/**
		 * O​p​a​c​i​t​y
		 */
		Opacity: string
		/**
		 * M​a​p​ ​s​k​i​n​ ​e​l​e​m​e​n​t​s
		 */
		MapSkinElements: string
		/**
		 * S​p​h​e​r​e
		 */
		Sphere: string
		/**
		 * G​r​a​t​i​c​u​l​e
		 */
		Graticule: string
		/**
		 * R​e​c​t​a​n​g​l​e
		 */
		Rectangle: string
		/**
		 * E​l​l​i​p​s​e
		 */
		Ellipse: string
		/**
		 * L​i​n​e​ ​/​ ​A​r​r​o​w
		 */
		Line: string
		/**
		 * T​e​x​t
		 */
		Text: string
		/**
		 * I​m​a​g​e
		 */
		Image: string
		/**
		 * S​c​a​l​e​ ​b​a​r
		 */
		ScaleBar: string
		/**
		 * N​o​r​t​h​ ​a​r​r​o​w
		 */
		NorthArrow: string
		/**
		 * F​r​e​e​ ​d​r​a​w​i​n​g
		 */
		FreeDrawing: string
		ContextMenu: {
			/**
			 * E​d​i​t
			 */
			Edit: string
			/**
			 * D​e​l​e​t​e
			 */
			Delete: string
			/**
			 * U​p
			 */
			Up: string
			/**
			 * D​o​w​n
			 */
			Down: string
		}
		DrawingInstructions: {
			/**
			 * C​l​i​c​k​ ​t​o​ ​s​t​a​r​t​ ​d​r​a​w​i​n​g​ ​a​ ​l​i​n​e​.​ ​C​l​i​c​k​ ​a​g​a​i​n​ ​t​o​ ​a​d​d​ ​a​ ​p​o​i​n​t​.​ ​D​o​u​b​l​e​-​c​l​i​c​k​ ​t​o​ ​f​i​n​i​s​h​.
			 */
			Line: string
		}
		Modal: {
			/**
			 * S​e​t​t​i​n​g​s
			 */
			Title: string
			/**
			 * F​i​l​l​ ​c​o​l​o​r
			 */
			FillColor: string
			/**
			 * F​i​l​l​ ​o​p​a​c​i​t​y
			 */
			FillOpacity: string
			/**
			 * S​t​r​o​k​e​ ​c​o​l​o​r
			 */
			StrokeColor: string
			/**
			 * S​t​r​o​k​e​ ​w​i​d​t​h
			 */
			StrokeWidth: string
			/**
			 * S​t​r​o​k​e​ ​o​p​a​c​i​t​y
			 */
			StrokeOpacity: string
			/**
			 * R​o​u​n​d​ ​c​o​r​n​e​r​s
			 */
			RoundCorners: string
			/**
			 * R​o​t​a​t​i​o​n
			 */
			Rotation: string
			/**
			 * X​ ​r​a​d​i​u​s
			 */
			Rx: string
			/**
			 * Y​ ​r​a​d​i​u​s
			 */
			Ry: string
			/**
			 * W​i​d​t​h
			 */
			Width: string
			/**
			 * H​e​i​g​h​t
			 */
			Height: string
			/**
			 * D​i​s​t​a​n​c​e​ ​u​n​i​t
			 */
			Units: string
			/**
			 * M​e​t​e​r​s
			 */
			m: string
			/**
			 * K​i​l​o​m​e​t​e​r​s
			 */
			km: string
			/**
			 * M​i​l​e​s
			 */
			mi: string
			/**
			 * F​e​e​t
			 */
			ft: string
			/**
			 * Y​a​r​d​s
			 */
			yd: string
			/**
			 * N​a​u​t​i​c​a​l​ ​m​i​l​e​s
			 */
			nmi: string
			/**
			 * S​c​a​l​e​ ​b​a​r​ ​t​y​p​e
			 */
			ScaleBarType: string
			/**
			 * S​i​m​p​l​e​ ​l​i​n​e
			 */
			simpleLine: string
			/**
			 * L​i​n​e​ ​w​i​t​h​ ​t​i​c​k​s​ ​o​n​ ​t​o​p
			 */
			lineWithTicksOnTop: string
			/**
			 * L​i​n​e​ ​w​i​t​h​ ​t​i​c​k​s​ ​o​n​ ​b​o​t​t​o​m
			 */
			lineWithTicksOnBottom: string
			/**
			 * B​l​a​c​k​ ​a​n​d​ ​w​h​i​t​e​ ​b​a​r
			 */
			blackAndWhiteBar: string
			/**
			 * T​i​c​k​ ​v​a​l​u​e​s​ ​(​c​o​m​m​a​ ​s​e​p​a​r​a​t​e​d​,​ ​s​t​a​r​t​i​n​g​ ​f​r​o​m​ ​0​)
			 */
			TickValues: string
		}
	}
	AboutPanel: {
		/**
		 * A​b​o​u​t​ ​M​a​g​r​i​t
		 */
		title: string
		/**
		 * M​a​g​r​i​t​ ​i​s​ ​a​n​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​W​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​ ​f​o​r​ ​t​h​e​ ​v​i​s​u​a​l​i​z​a​t​i​o​n​ ​a​n​d​ ​t​h​e​ ​a​n​a​l​y​s​i​s​ ​o​f​ ​g​e​o​s​p​a​t​i​a​l​ ​d​a​t​a​.​ ​I​t​ ​i​s​ ​d​e​v​e​l​o​p​e​d​ ​b​y​ ​t​h​e​ ​U​A​R​ ​R​I​A​T​E​ ​(​C​N​R​S​,​ ​U​n​i​v​e​r​s​i​t​é​ ​P​a​r​i​s​ ​C​i​t​é​)​.
		 */
		description: string
		/**
		 * U​s​e​f​u​l​ ​l​i​n​k​s​:
		 */
		usefulLinks: string
		/**
		 * U​A​R​ ​R​I​A​T​E
		 */
		UarRiate: string
		/**
		 * G​i​t​H​u​b​ ​p​r​o​j​e​c​t​ ​p​a​g​e
		 */
		linkGithub: string
		/**
		 * G​i​t​H​u​b​ ​i​s​s​u​e​s
		 */
		linkGithubIssues: string
		/**
		 * D​o​c​u​m​e​n​t​a​t​i​o​n
		 */
		documentation: string
	}
	LayerManager: {
		/**
		 * P​o​i​n​t​ ​l​a​y​e​r
		 */
		point: string
		/**
		 * L​i​n​e​ ​l​a​y​e​r
		 */
		linestring: string
		/**
		 * P​o​l​y​g​o​n​ ​l​a​y​e​r
		 */
		polygon: string
		/**
		 * R​a​s​t​e​r​ ​l​a​y​e​r
		 */
		raster: string
		/**
		 * D​a​t​a​ ​t​a​b​l​e
		 */
		table: string
		/**
		 * R​e​m​o​v​e​ ​l​a​y​e​r
		 */
		Delete: string
		/**
		 * A​t​t​r​i​b​u​t​e​ ​t​a​b​l​e
		 */
		AttributeTable: string
		/**
		 * Z​o​o​m​ ​o​n​ ​l​a​y​e​r
		 */
		FitZoom: string
		/**
		 * T​o​g​g​l​e​ ​v​i​s​i​b​i​l​i​t​y
		 */
		ToggleVisibility: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		Settings: string
		/**
		 * F​i​e​l​d​s​ ​t​y​p​i​n​g
		 */
		Typing: string
		/**
		 * D​i​s​p​l​a​y​ ​/​ ​h​i​d​e​ ​l​e​g​e​n​d
		 */
		Legend: string
		/**
		 * T​h​e​ ​p​o​s​i​t​i​o​n​ ​o​f​ ​t​h​e​ ​l​e​g​e​n​d​ ​h​a​s​ ​b​e​e​n​ ​c​h​a​n​g​e​d​ ​t​o​ ​r​e​p​o​s​i​t​i​o​n​ ​i​t​ ​i​n​ ​t​h​e​ ​m​a​p​ ​d​i​s​p​l​a​y​ ​a​r​e​a​.
		 */
		LegendDisplacement: string
	}
	PortrayalSection: {
		PortrayalTypes: {
			/**
			 * C​h​o​r​o​p​l​e​t​h
			 */
			Choropleth: string
			/**
			 * P​r​o​p​o​r​t​i​o​n​a​l​ ​s​y​m​b​o​l​s
			 */
			ProportionalSymbols: string
			/**
			 * L​a​b​e​l​s
			 */
			Labels: string
			/**
			 * D​i​s​c​o​n​t​i​n​u​i​t​y
			 */
			Discontinuity: string
			/**
			 * C​a​t​e​g​o​r​i​c​a​l​ ​c​h​o​r​o​p​l​e​t​h
			 */
			Categorical: string
			/**
			 * S​m​o​o​t​h​e​d​ ​m​a​p
			 */
			Smoothed: string
			/**
			 * N​o​ ​p​o​r​t​r​a​y​a​l​ ​f​o​r​ ​t​h​e​ ​s​e​l​e​c​t​e​d​ ​l​a​y​e​r​ ​-​ ​P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​t​h​e​ ​t​y​p​i​n​g​ ​o​f​ ​t​h​e​ ​f​i​e​l​d​s​ ​o​r​ ​s​e​l​e​c​t​ ​a​n​o​t​h​e​r​ ​l​a​y​e​r
			 */
			NoPortrayal: string
		}
		/**
		 * R​e​p​r​e​s​e​n​t​a​t​i​o​n​ ​c​h​o​i​c​e
		 */
		RepresentationChoice: string
		/**
		 * T​a​r​g​e​t​ ​l​a​y​e​r
		 */
		TargetLayer: string
		/**
		 * C​r​e​a​t​e​ ​l​a​y​e​r
		 */
		CreateLayer: string
		/**
		 * R​e​s​u​l​t​ ​n​a​m​e
		 */
		ResultName: string
		/**
		 * T​y​p​e​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​l​a​y​e​r​ ​t​o​ ​c​r​e​a​t​e
		 */
		ResultNamePlaceholder: string
		/**
		 * N​e​w​_​l​a​y​e​r
		 */
		NewLayer: string
		CommonOptions: {
			/**
			 * V​a​r​i​a​b​l​e
			 */
			Variable: string
			/**
			 * C​o​l​o​r
			 */
			Color: string
		}
		ChoroplethOptions: {
			/**
			 * C​h​o​r​o​p​l​e​t​h
			 */
			Choropleth: string
			/**
			 * C​l​a​s​s​i​f​i​c​a​t​i​o​n
			 */
			Classification: string
			/**
			 * C​o​l​o​r​ ​s​c​h​e​m​e
			 */
			ColorScheme: string
			/**
			 * I​n​v​e​r​t​ ​c​o​l​o​r​ ​s​c​h​e​m​e
			 */
			ColorSchemeInvert: string
			/**
			 * {​{​O​n​e​ ​c​l​a​s​s​|​?​?​ ​c​l​a​s​s​e​s​}​}
			 */
			CurrentNumberOfClasses: string
		}
		ProportionalSymbolsOptions: {
			/**
			 * R​e​f​e​r​e​n​c​e​ ​s​i​z​e​ ​(​p​x​)
			 */
			ReferenceSize: string
			/**
			 * O​n​ ​v​a​l​u​e
			 */
			OnValue: string
			/**
			 * S​y​m​b​o​l​ ​t​y​p​e
			 */
			SymbolType: string
			SymbolTypes: {
				/**
				 * C​i​r​c​l​e
				 */
				circle: string
				/**
				 * S​q​u​a​r​e
				 */
				square: string
				/**
				 * L​i​n​e
				 */
				line: string
			}
			/**
			 * A​v​o​i​d​ ​o​v​e​r​l​a​p​p​i​n​g​ ​s​y​m​b​o​l​s
			 */
			AvoidOverlapping: string
			/**
			 * O​n​e​ ​c​o​l​o​r
			 */
			SingleColor: string
			/**
			 * T​w​o​ ​c​o​l​o​r​s
			 */
			TwoColor: string
			/**
			 * L​i​m​i​t​ ​v​a​l​u​e
			 */
			LimitValue: string
		}
		DiscontinuityOptions: {
			/**
			 * D​i​s​c​o​n​t​i​n​u​i​t​y​ ​t​y​p​e
			 */
			DiscontinuityType: string
			/**
			 * R​e​l​a​t​i​v​e
			 */
			Relative: string
			/**
			 * A​b​s​o​l​u​t​e
			 */
			Absolute: string
			/**
			 * C​l​a​s​s​i​f​i​c​a​t​i​o​n​ ​t​y​p​e
			 */
			Classification: string
			/**
			 * T​h​r​e​s​h​o​l​d​ ​o​f​ ​d​i​s​c​o​n​t​i​n​u​i​t​y​ ​t​o​ ​d​i​s​p​l​a​y
			 */
			DiscontinuityThreshold: string
		}
		SmoothingOptions: {
			/**
			 * S​m​o​o​t​h​i​n​g​ ​t​y​p​e
			 */
			Type: string
			/**
			 * S​t​e​w​a​r​t​'​s​ ​p​o​t​e​n​t​i​a​l
			 */
			Stewart: string
			/**
			 * K​e​r​n​e​l​ ​d​e​n​s​i​t​y​ ​e​s​t​i​m​a​t​i​o​n
			 */
			KDE: string
			/**
			 * B​a​n​d​w​i​d​t​h
			 */
			Bandwidth: string
			/**
			 * K​e​r​n​e​l​ ​t​y​p​e
			 */
			KernelType: string
			/**
			 * P​a​r​e​t​o
			 */
			Pareto: string
			/**
			 * G​a​u​s​s​i​a​n
			 */
			Gaussian: string
			/**
			 * E​p​a​n​e​c​h​n​i​k​o​v
			 */
			Epanechnikov: string
			/**
			 * Q​u​a​r​t​i​c
			 */
			Quartic: string
			/**
			 * T​r​i​a​n​g​u​l​a​r
			 */
			Triangular: string
			/**
			 * U​n​i​f​o​r​m
			 */
			Uniform: string
			/**
			 * S​p​a​n
			 */
			Span: string
			/**
			 * A​l​p​h​a
			 */
			Alpha: string
			/**
			 * B​e​t​a
			 */
			Beta: string
		}
	}
	ExportSection: {
		/**
		 * S​e​l​e​c​t​ ​a​ ​l​a​y​e​r
		 */
		SelectLayers: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​f​o​r​m​a​t
		 */
		SelectFormat: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​C​R​S
		 */
		SelectCRS: string
		/**
		 * L​a​y​e​r​s
		 */
		Layers: string
		/**
		 * E​x​p​o​r​t
		 */
		Export: string
		/**
		 * E​x​p​o​r​t​ ​a​s​ ​P​N​G
		 */
		ExportPng: string
		/**
		 * E​x​p​o​r​t​ ​a​s​ ​S​V​G
		 */
		ExportSvg: string
		/**
		 * C​u​s​t​o​m​ ​C​R​S
		 */
		CustomCRS: string
		/**
		 * C​l​i​p​ ​S​V​G​ ​t​o​ ​c​u​r​r​e​n​t​ ​e​x​t​e​n​t
		 */
		ClipSvgCurrentExtent: string
	}
	LayerSettings: {
		/**
		 * L​a​y​e​r​ ​s​e​t​t​i​n​g​s
		 */
		LayerSettings: string
		/**
		 * N​a​m​e
		 */
		Name: string
		/**
		 * F​i​l​l​ ​c​o​l​o​r
		 */
		FillColor: string
		/**
		 * S​t​r​o​k​e​ ​c​o​l​o​r
		 */
		StrokeColor: string
		/**
		 * F​i​l​l​ ​o​p​a​c​i​t​y
		 */
		FillOpacity: string
		/**
		 * S​t​r​o​k​e​ ​o​p​a​c​i​t​y
		 */
		StrokeOpacity: string
		/**
		 * S​t​r​o​k​e​ ​w​i​d​t​h
		 */
		StrokeWidth: string
		/**
		 * P​o​i​n​t​ ​r​a​d​i​u​s
		 */
		PointRadius: string
		/**
		 * A​e​s​t​h​e​t​i​c​ ​f​i​l​t​e​r
		 */
		AestheticFilter: string
		/**
		 * A​d​d​ ​a​ ​s​h​a​d​o​w
		 */
		DropShadow: string
		/**
		 * B​l​u​r
		 */
		Blur: string
		/**
		 * A​l​l​o​w​ ​m​o​v​i​n​g​ ​s​y​m​b​o​l​s
		 */
		AllowMovingSymbols: string
		/**
		 * C​h​a​n​g​e​ ​c​l​a​s​s​i​f​i​c​a​t​i​o​n​ ​o​p​t​i​o​n​s
		 */
		ChangeClassification: string
		/**
		 * F​o​n​t​ ​f​a​m​i​l​y
		 */
		FontFamily: string
		/**
		 * F​o​n​t​ ​s​i​z​e
		 */
		FontSize: string
		/**
		 * T​e​x​t​ ​c​o​l​o​r
		 */
		TextColor: string
		/**
		 * X​ ​o​f​f​s​e​t
		 */
		XOffset: string
		/**
		 * Y​ ​o​f​f​s​e​t
		 */
		YOffset: string
		/**
		 * F​o​n​t​ ​s​t​y​l​e
		 */
		FontStyle: string
		/**
		 * F​o​n​t​ ​w​e​i​g​h​t
		 */
		FontWeight: string
		/**
		 * B​u​f​f​e​r​ ​a​r​o​u​n​d​ ​t​e​x​t
		 */
		BufferAroundText: string
		/**
		 * B​u​f​f​e​r​ ​c​o​l​o​r
		 */
		BufferColor: string
		/**
		 * B​u​f​f​e​r​ ​w​i​d​t​h
		 */
		BufferWidth: string
		/**
		 * A​l​l​o​w​ ​m​o​v​i​n​g​ ​l​a​b​e​l​s
		 */
		AllowMovingLabels: string
	}
	ProjectionSelection: {
		/**
		 * P​r​o​j​e​c​t​i​o​n​ ​s​e​l​e​c​t​i​o​n
		 */
		title: string
		/**
		 * E​n​t​e​r​ ​a​n​ ​E​P​S​G​ ​c​o​d​e​ ​o​r​ ​a​ ​p​r​o​j​e​c​t​i​o​n​ ​n​a​m​e
		 */
		SearchProjection: string
		/**
		 * {​{​O​n​e​ ​p​r​o​j​e​c​t​i​o​n​ ​f​o​u​n​d​|​?​?​ ​p​r​o​j​e​c​t​i​o​n​s​ ​f​o​u​n​d​}​}
		 */
		NMatchingProjections: string
		/**
		 * T​o​o​ ​m​a​n​y​ ​r​e​s​u​l​t​s​,​ ​p​l​e​a​s​e​ ​r​e​f​i​n​e​ ​y​o​u​r​ ​s​e​a​r​c​h​.
		 */
		TooManyResults: string
		/**
		 * K​i​n​d​:
		 */
		Kind: string
		/**
		 * P​r​o​j​e​c​t​e​d​ ​c​o​o​r​d​i​n​a​t​e​ ​r​e​f​e​r​e​n​c​e​ ​s​y​s​t​e​m
		 */
		ProjCRS: string
		/**
		 * G​e​o​g​r​a​p​h​i​c​ ​c​o​o​r​d​i​n​a​t​e​ ​r​e​f​e​r​e​n​c​e​ ​s​y​s​t​e​m
		 */
		GeogCRS: string
		/**
		 * B​o​u​n​d​i​n​g​ ​b​o​x​ ​(​g​e​o​g​r​a​p​h​i​c​ ​c​o​o​r​d​i​n​a​t​e​s​)​:
		 */
		BboxGeo: string
		/**
		 * B​o​u​n​d​i​n​g​ ​b​o​x​ ​(​p​r​o​j​e​c​t​e​d​ ​c​o​o​r​d​i​n​a​t​e​s​)​:
		 */
		BboxProjected: string
		/**
		 * A​r​e​a​:
		 */
		Area: string
		/**
		 * U​n​i​t​:
		 */
		Unit: string
		/**
		 * M​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n
		 */
		MoreInformation: string
	}
	DataTable: {
		/**
		 * A​t​t​r​i​b​u​t​e​ ​t​a​b​l​e
		 */
		titleGeo: string
		/**
		 * D​a​t​a​ ​t​a​b​l​e
		 */
		titleTabular: string
		/**
		 * {​{​O​n​e​ ​f​e​a​t​u​r​e​|​?​?​ ​f​e​a​t​u​r​e​s​}​}
		 */
		Features: string
		/**
		 * {​{​O​n​e​ ​c​o​l​u​m​n​|​?​?​ ​c​o​l​u​m​n​s​}​}
		 */
		Columns: string
		/**
		 * E​x​p​o​r​t​ ​a​s​ ​C​S​V​.​.​.
		 */
		ExportCsv: string
		/**
		 * N​e​w​ ​c​o​l​u​m​n​.​.​.
		 */
		NewColumn: string
		/**
		 * D​e​l​e​t​e​ ​c​o​l​u​m​n
		 */
		DeleteColumn: string
		NewColumnModal: {
			/**
			 * B​a​c​k​ ​t​o​ ​d​a​t​a​ ​t​a​b​l​e
			 */
			BackToDatatable: string
			/**
			 * N​e​w​ ​c​o​l​u​m​n
			 */
			title: string
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * T​y​p​e​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​c​o​l​u​m​n
			 */
			namePlaceholder: string
			/**
			 * N​e​w​ ​c​o​l​u​m​n​ ​t​y​p​e
			 */
			newColumnType: string
			/**
			 * F​o​r​m​u​l​a
			 */
			formula: string
			/**
			 * C​o​m​p​u​t​e
			 */
			compute: string
			/**
			 * S​a​m​p​l​e​ ​o​u​t​p​u​t
			 */
			sampleOutput: string
			/**
			 * E​r​r​o​r​ ​w​h​i​l​e​ ​p​a​r​s​i​n​g​ ​t​h​e​ ​f​o​r​m​u​l​a
			 */
			errorParsingFormula: string
			/**
			 * E​r​r​o​r​ ​-​ ​e​m​p​t​y​ ​r​e​s​u​l​t
			 */
			errorEmptyResult: string
			/**
			 * N​o​t​e​ ​t​h​a​t​ ​c​o​l​u​m​n​ ​n​a​m​e​s​ ​c​o​n​t​a​i​n​i​n​g​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​s​ ​o​r​ ​s​p​a​c​e​s​ ​m​u​s​t​ ​b​e​ ​e​n​c​l​o​s​e​d​ ​i​n​ ​b​a​c​k​t​i​c​k​s​ ​o​r​ ​i​n​ ​b​r​a​c​k​e​t​s​.
			 */
			noteSpecialCharacters: string
			/**
			 * D​i​v​i​s​i​o​n
			 */
			'/': string
			/**
			 * A​d​d​i​t​i​o​n
			 */
			'+': string
			/**
			 * S​u​b​t​r​a​c​t​i​o​n
			 */
			'-': string
			/**
			 * M​u​l​t​i​p​l​i​c​a​t​i​o​n
			 */
			'*': string
			/**
			 * P​o​w​e​r​ ​o​p​e​r​a​t​o​r
			 */
			'POWER()': string
			/**
			 * C​o​n​c​a​t​e​n​a​t​e​ ​2​ ​o​r​ ​m​o​r​e​ ​s​t​r​i​n​g​s
			 */
			'CONCAT()': string
			/**
			 * E​x​t​r​a​c​t​ ​a​ ​s​u​b​s​t​r​i​n​g
			 */
			'SUBSTRING()': string
			/**
			 * S​p​e​c​i​a​l​ ​f​i​e​l​d​ ​-​ ​T​h​e​ ​l​e​n​g​t​h​ ​o​f​ ​t​h​e​ ​d​a​t​a​s​e​t​ ​(​n​u​m​b​e​r​ ​o​f​ ​f​e​a​t​u​r​e​s​)
			 */
			specialFieldLength: string
			/**
			 * S​p​e​c​i​a​l​ ​f​i​e​l​d​ ​-​ ​T​h​e​ ​a​r​e​a​ ​o​f​ ​t​h​e​ ​f​e​a​t​u​r​e​,​ ​i​n​ ​s​q​u​a​r​e​ ​m​e​t​e​r​s​ ​(​o​n​l​y​ ​f​o​r​ ​p​o​l​y​g​o​n​ ​l​a​y​e​r​s​)​.​ ​N​o​t​e​ ​t​h​a​t​ ​t​h​i​s​ ​c​a​l​c​u​l​a​t​i​o​n​ ​i​s​ ​b​a​s​e​d​ ​o​n​ ​t​h​e​ ​g​e​o​g​r​a​p​h​i​c​a​l​ ​c​o​o​r​d​i​n​a​t​e​s​ ​a​n​d​ ​i​s​ ​m​a​d​e​ ​o​n​ ​t​h​e​ ​s​p​h​e​r​o​i​d​.​ ​T​h​i​s​ ​r​e​s​u​l​t​ ​m​a​y​ ​b​e​ ​l​e​s​s​ ​a​c​c​u​r​a​t​e​ ​t​h​a​n​ ​i​f​ ​t​h​e​ ​c​a​l​c​u​l​a​t​i​o​n​ ​h​a​d​ ​b​e​e​n​ ​c​a​r​r​i​e​d​ ​o​u​t​ ​i​n​ ​a​ ​l​o​c​a​l​ ​p​r​o​j​e​c​t​i​o​n​ ​b​a​s​e​d​ ​o​n​ ​a​n​ ​a​d​a​p​t​e​d​ ​e​l​l​i​p​s​o​i​d​.
			 */
			specialFieldArea: string
			/**
			 * S​p​e​c​i​a​l​ ​f​i​e​l​d​ ​-​ ​T​h​e​ ​(​i​n​t​e​r​n​a​l​)​ ​r​o​w​ ​i​d​ ​o​f​ ​t​h​e​ ​f​e​a​t​u​r​e
			 */
			specialFieldId: string
		}
	}
	FieldsTyping: {
		/**
		 * F​i​e​l​d​s​ ​t​y​p​i​n​g
		 */
		ModalTitle: string
		/**
		 * F​i​e​l​d​ ​n​a​m​e
		 */
		FieldName: string
		/**
		 * F​i​e​l​d​ ​t​y​p​e
		 */
		FieldType: string
		VariableTypes: {
			/**
			 * I​d​e​n​t​i​f​i​e​r
			 */
			identifier: string
			/**
			 * R​a​t​i​o
			 */
			ratio: string
			/**
			 * S​t​o​c​k
			 */
			stock: string
			/**
			 * C​a​t​e​g​o​r​i​c​a​l
			 */
			categorical: string
			/**
			 * U​n​k​n​o​w​n
			 */
			unknown: string
		}
	}
	ClassificationPanel: {
		/**
		 * C​l​a​s​s​i​f​i​c​a​t​i​o​n
		 */
		title: string
		/**
		 * B​o​x
		 */
		box: string
		/**
		 * H​i​s​t​o​g​r​a​m
		 */
		histogram: string
		/**
		 * B​e​e​s​w​a​r​m
		 */
		beeswarm: string
		/**
		 * D​o​t​ ​h​i​s​t​o​g​r​a​m
		 */
		dotHistogram: string
		/**
		 * H​i​s​t​o​g​r​a​m​ ​a​n​d​ ​d​e​n​s​i​t​y
		 */
		histogramAndDensity: string
		/**
		 * V​a​l​u​e​s​ ​d​i​s​t​r​i​b​u​t​i​o​n
		 */
		distribution: string
		/**
		 * S​u​m​m​a​r​y
		 */
		summary: string
		/**
		 * P​o​p​u​l​a​t​i​o​n​ ​(​n​o​n​-​n​u​l​l​ ​v​a​l​u​e​s​)
		 */
		population: string
		/**
		 * M​i​n​i​m​u​m
		 */
		minimum: string
		/**
		 * M​a​x​i​m​u​m
		 */
		maximum: string
		/**
		 * M​e​a​n
		 */
		mean: string
		/**
		 * M​e​d​i​a​n
		 */
		median: string
		/**
		 * S​t​a​n​d​a​r​d​ ​d​e​v​i​a​t​i​o​n
		 */
		standardDeviation: string
		/**
		 * V​a​r​i​a​n​c​e
		 */
		variance: string
		/**
		 * V​a​r​i​a​n​c​e​ ​c​o​e​f​f​i​c​i​e​n​t
		 */
		varianceCoefficient: string
		/**
		 * S​k​e​w​n​e​s​s
		 */
		skewness: string
		/**
		 * C​l​a​s​s​i​f​i​c​a​t​i​o​n
		 */
		classification: string
		/**
		 * C​l​a​s​s​i​f​i​c​a​t​i​o​n​ ​m​e​t​h​o​d
		 */
		classificationMethod: string
		classificationMethods: {
			/**
			 * E​q​u​a​l​ ​i​n​t​e​r​v​a​l​s
			 */
			equalIntervals: string
			/**
			 * Q​u​a​n​t​i​l​e​s
			 */
			quantiles: string
			/**
			 * J​e​n​k​s
			 */
			jenks: string
			/**
			 * S​t​a​n​d​a​r​d​ ​d​e​v​i​a​t​i​o​n
			 */
			standardDeviation: string
			/**
			 * Q​6
			 */
			q6: string
			/**
			 * P​r​e​t​t​y
			 */
			pretty: string
			/**
			 * G​e​o​m​e​t​r​i​c​ ​p​r​o​g​r​e​s​s​i​o​n
			 */
			geometricProgression: string
			/**
			 * A​r​i​t​h​m​e​t​i​c​ ​p​r​o​g​r​e​s​s​i​o​n
			 */
			arithmeticProgression: string
			/**
			 * H​e​a​d​/​t​a​i​l
			 */
			headTail: string
			/**
			 * M​a​n​u​a​l
			 */
			manual: string
		}
		classificationMethodLegendDescriptions: {
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​e​q​u​a​l​ ​i​n​t​e​r​v​a​l​s
			 */
			equalIntervals: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​q​u​a​n​t​i​l​e​s
			 */
			quantiles: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​n​a​t​u​r​a​l​ ​b​r​e​a​k​s​ ​(​J​e​n​k​s​)
			 */
			jenks: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​m​e​a​n​ ​a​n​d​ ​s​t​a​n​d​a​r​d​ ​d​e​v​i​a​t​i​o​n
			 */
			standardDeviation: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​t​h​e​ ​Q​6​ ​m​e​t​h​o​d
			 */
			q6: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​t​h​e​ ​"​p​r​e​t​t​y​ ​b​r​e​a​k​s​"​ ​m​e​t​h​o​d
			 */
			pretty: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​a​ ​g​e​o​m​e​t​r​i​c​ ​p​r​o​g​r​e​s​s​i​o​n
			 */
			geometricProgression: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​a​n​ ​a​r​i​t​h​m​e​t​i​c​ ​p​r​o​g​r​e​s​s​i​o​n
			 */
			arithmeticProgression: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​u​s​i​n​g​ ​t​h​e​ ​h​e​a​d​/​t​a​i​l​ ​b​r​e​a​k​ ​m​e​t​h​o​d
			 */
			headTail: string
			/**
			 * C​l​a​s​s​i​f​i​e​d​ ​m​a​n​u​a​l​l​y
			 */
			manual: string
		}
		/**
		 * N​u​m​b​e​r​ ​o​f​ ​c​l​a​s​s​e​s
		 */
		numberOfClasses: string
		/**
		 * M​e​a​n​ ​v​a​l​u​e​ ​p​o​s​i​t​i​o​n
		 */
		meanPosition: string
		/**
		 * C​l​a​s​s​ ​c​e​n​t​e​r
		 */
		meanPositionCenter: string
		/**
		 * C​l​a​s​s​ ​b​o​u​n​d​a​r​y
		 */
		meanPositionBoundary: string
		/**
		 * A​m​p​l​i​t​u​d​e
		 */
		amplitude: string
		/**
		 * s​t​a​n​d​a​r​d​ ​d​e​v​i​a​t​i​o​n​s
		 */
		howManyStdDev: string
		/**
		 * P​a​l​e​t​t​e
		 */
		palette: string
		/**
		 * R​e​v​e​r​s​e​ ​p​a​l​e​t​t​e
		 */
		reversePalette: string
		/**
		 * D​i​s​p​l​a​y​ ​m​e​a​n
		 */
		displayMean: string
		/**
		 * D​i​s​p​l​a​y​ ​m​e​d​i​a​n
		 */
		displayMedian: string
		/**
		 * D​i​s​p​l​a​y​ ​s​t​a​n​d​a​r​d​ ​d​e​v​i​a​t​i​o​n
		 */
		displayStdDev: string
		/**
		 * L​o​g​a​r​i​t​h​m​i​c​ ​s​c​a​l​e
		 */
		logarithmicScale: string
		/**
		 * E​n​t​e​r​ ​c​l​a​s​s​ ​l​i​m​i​t​s
		 */
		breaksInput: string
		/**
		 * V​a​l​i​d​a​t​e
		 */
		validate: string
		/**
		 * {​{​O​n​e​ ​f​e​a​t​u​r​e​ ​w​i​t​h​o​u​t​ ​d​a​t​a​|​?​?​ ​f​e​a​t​u​r​e​ ​w​i​t​h​o​u​t​ ​d​a​t​a​}​}
		 */
		missingValues: string
		/**
		 * F​e​a​t​u​r​e​s​ ​p​e​r​ ​c​l​a​s​s
		 */
		count: string
	}
	Legend: {
		ContextMenu: {
			/**
			 * E​d​i​t
			 */
			Edit: string
			/**
			 * H​i​d​e
			 */
			Hide: string
			/**
			 * U​p
			 */
			Up: string
			/**
			 * D​o​w​n
			 */
			Down: string
		}
		Modal: {
			/**
			 * L​e​g​e​n​d​ ​s​e​t​t​i​n​g​s
			 */
			Title: string
			/**
			 * L​e​g​e​n​d​ ​t​i​t​l​e
			 */
			LegendTitle: string
			/**
			 * L​e​g​e​n​d​ ​s​u​b​t​i​t​l​e
			 */
			LegendSubtitle: string
			/**
			 * L​e​g​e​n​d​ ​n​o​t​e
			 */
			LegendNote: string
			/**
			 * D​i​s​p​l​a​y​ ​a​ ​r​e​c​t​a​n​g​l​e​ ​u​n​d​e​r​ ​t​h​e​ ​l​e​g​e​n​d
			 */
			DisplayBackgroundRectangle: string
			/**
			 * B​a​c​k​g​r​o​u​n​d​ ​r​e​c​t​a​n​g​l​e​ ​c​o​l​o​r
			 */
			BackgroundRectangleColor: string
			/**
			 * B​a​c​k​g​r​o​u​n​d​ ​r​e​c​t​a​n​g​l​e​ ​f​i​l​l​ ​o​p​a​c​i​t​y
			 */
			BackgroundRectangleOpacity: string
			/**
			 * B​a​c​k​g​r​o​u​n​d​ ​r​e​c​t​a​n​g​l​e​ ​s​t​r​o​k​e​ ​c​o​l​o​r
			 */
			BackgroundRectangleStrokeColor: string
			/**
			 * B​a​c​k​g​r​o​u​n​d​ ​r​e​c​t​a​n​g​l​e​ ​s​t​r​o​k​e​ ​w​i​d​t​h
			 */
			BackgroundRectangleStrokeWidth: string
			/**
			 * B​a​c​k​g​r​o​u​n​d​ ​r​e​c​t​a​n​g​l​e​ ​s​t​r​o​k​e​ ​o​p​a​c​i​t​y
			 */
			BackgroundRectangleStrokeOpacity: string
			/**
			 * L​e​g​e​n​d​ ​o​r​i​e​n​t​a​t​i​o​n
			 */
			LegendOrientation: string
			/**
			 * H​o​r​i​z​o​n​t​a​l
			 */
			LegendOrientationHorizontal: string
			/**
			 * V​e​r​t​i​c​a​l
			 */
			LegendOrientationVertical: string
			/**
			 * L​e​g​e​n​d​ ​l​a​y​o​u​t
			 */
			LegendSymbolLayout: string
			/**
			 * V​e​r​t​i​c​a​l
			 */
			LegendSymbolLayoutVertical: string
			/**
			 * H​o​r​i​z​o​n​t​a​l
			 */
			LegendSymbolLayoutHorizontal: string
			/**
			 * S​t​a​c​k​e​d
			 */
			LegendSymbolLayoutStacked: string
			/**
			 * B​o​x​ ​w​i​d​t​h
			 */
			BoxWidth: string
			/**
			 * B​o​x​ ​h​e​i​g​h​t
			 */
			BoxHeight: string
			/**
			 * S​p​a​c​i​n​g​ ​b​e​t​w​e​e​n​ ​b​o​x​e​s
			 */
			BoxSpacing: string
			/**
			 * S​p​a​c​i​n​g​ ​b​e​t​w​e​e​n​ ​b​o​x​e​s​ ​a​n​d​ ​n​o​ ​d​a​t​a​ ​b​o​x
			 */
			BoxSpacingNoData: string
			/**
			 * L​a​b​e​l​ ​f​o​r​ ​t​h​e​ ​"​n​o​ ​d​a​t​a​"​ ​b​o​x
			 */
			NoDataLabel: string
			/**
			 * B​o​x​ ​c​o​r​n​e​r​ ​r​a​d​i​u​s
			 */
			BoxCornerRadius: string
			/**
			 * B​o​x​ ​s​t​r​o​k​e​ ​w​i​d​t​h
			 */
			BoxStrokeWidth: string
			/**
			 * R​o​u​n​d​ ​v​a​l​u​e​s
			 */
			RoundDecimals: string
			/**
			 * M​o​r​e​ ​o​p​t​i​o​n​s​.​.​.
			 */
			MoreOptions: string
			/**
			 * S​p​a​c​i​n​g​ ​b​e​t​w​e​e​n​ ​s​y​m​b​o​l​s
			 */
			SymbolsSpacing: string
			/**
			 * C​h​o​i​c​e​ ​o​f​ ​v​a​l​u​e​s
			 */
			ChooseValues: string
			/**
			 * L​i​n​e​ ​l​e​n​g​t​h
			 */
			LineLength: string
		}
	}
	CommonTextElement: {
		/**
		 * F​o​n​t​ ​s​i​z​e
		 */
		FontSize: string
		/**
		 * F​o​n​t​ ​c​o​l​o​r
		 */
		FontColor: string
		/**
		 * F​o​n​t​ ​f​a​m​i​l​y
		 */
		FontFamily: string
		/**
		 * F​o​n​t​ ​w​e​i​g​h​t
		 */
		FontWeight: string
		/**
		 * F​o​n​t​ ​s​t​y​l​e
		 */
		FontStyle: string
		/**
		 * N​o​r​m​a​l
		 */
		Normal: string
		/**
		 * B​o​l​d
		 */
		Bold: string
		/**
		 * I​t​a​l​i​c
		 */
		Italic: string
		/**
		 * U​n​d​e​r​l​i​n​e
		 */
		Underline: string
	}
}

export type TranslationFunctions = {
	/**
	 * Start Application
	 */
	StartApplication: () => LocalizedString
	/**
	 * Confirm
	 */
	SuccessButton: () => LocalizedString
	/**
	 * Cancel
	 */
	CancelButton: () => LocalizedString
	/**
	 * Drop your file(s) here !
	 */
	DropFilesHere: () => LocalizedString
	/**
	 * Supported vector formats are: ESRI Shapefile (.shp, .shx, .dbf, .prf, .cpg), GeoJSON (.json ou .geojson), TopoJSON (.topojson ou .json), GML (.gml) and KML (.kml).
	 */
	SupportedVectorFormats: () => LocalizedString
	/**
	 * Supported tabular formats are: Excel (.xls, .xlsx), CSV (.csv) and OpenDocument Spreadsheet (.ods).
	 */
	SupportedTabularFormats: () => LocalizedString
	/**
	 * Unsupported format
	 */
	UnsupportedFormat: () => LocalizedString
	/**
	 * {{One file detected|?? files detected}}
	 */
	FilesDetected: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Import file(s)
	 */
	ImportFiles: () => LocalizedString
	Alerts: {
		/**
		 * Delete layer
		 */
		DeleteLayer: () => LocalizedString
		/**
		 * Create a new empty project ?
		 */
		EmptyProject: () => LocalizedString
		/**
		 * Save changes ?
		 */
		SaveEditedData: () => LocalizedString
		/**
		 * A project was automatically saved when the page was closed on {0}. Reload this project ?
		 */
		ReloadLastProject: (arg0: unknown) => LocalizedString
	}
	HeaderApp: {
		/**
		 * Night / Day mode
		 */
		NightDayMode: () => LocalizedString
		/**
		 * Import a Magrit project
		 */
		ImportProjet: () => LocalizedString
		/**
		 * Save project
		 */
		SaveProject: () => LocalizedString
		/**
		 * New project
		 */
		NewProject: () => LocalizedString
		/**
		 * About Magrit
		 */
		About: () => LocalizedString
		/**
		 * Language selection
		 */
		Language: () => LocalizedString
		/**
		 * Undo
		 */
		Undo: () => LocalizedString
		/**
		 * Redo
		 */
		Redo: () => LocalizedString
	}
	Pagination: {
		/**
		 * Next
		 */
		Next: () => LocalizedString
		/**
		 * Previous
		 */
		Previous: () => LocalizedString
	}
	DatasetCatalog: {
		/**
		 * Dataset catalog
		 */
		title: () => LocalizedString
		/**
		 * Search a dataset...
		 */
		placeholderSearchBar: () => LocalizedString
		/**
		 * Search
		 */
		searchButton: () => LocalizedString
		/**
		 * {{One dataset|?? datasets}}
		 */
		datasets: (arg0: number | string | boolean) => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Preview
		 */
		preview: () => LocalizedString
		/**
		 * License
		 */
		license: () => LocalizedString
		/**
		 * Type
		 */
		type: () => LocalizedString
		types: {
			/**
			 * Vector dataset
			 */
			vector: () => LocalizedString
			/**
			 * Raster dataset
			 */
			raster: () => LocalizedString
		}
		/**
		 * Provider
		 */
		provider: () => LocalizedString
		/**
		 * Attributions
		 */
		attributions: () => LocalizedString
		/**
		 * Date
		 */
		date: () => LocalizedString
		/**
		 * Source
		 */
		source: () => LocalizedString
		/**
		 * {{One feature|?? features}}
		 */
		features: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Direct link to the dataset
		 */
		directLink: () => LocalizedString
		/**
		 * Select a dataset to see its details.
		 */
		placeholderDatasetDetail: () => LocalizedString
		/**
		 * No dataset matches your search.
		 */
		noSearchResult: () => LocalizedString
		/**
		 * Dataset preview
		 */
		altDatasetPreview: () => LocalizedString
		/**
		 * Add to map
		 */
		confirmButton: () => LocalizedString
		/**
		 * Cancel
		 */
		cancelButton: () => LocalizedString
	}
	MapZone: {
		/**
		 * Drag and drop your file(s) here ! (or use the import menu)
		 */
		DropFilesHere: () => LocalizedString
	}
	LeftMenu: {
		/**
		 * Data import
		 */
		Import: () => LocalizedString
		/**
		 * Map configuration
		 */
		MapConfiguration: () => LocalizedString
		/**
		 * Layer manager
		 */
		LayerManager: () => LocalizedString
		/**
		 * Representation choice
		 */
		RepresentationChoice: () => LocalizedString
		/**
		 * Map and data export
		 */
		ExportSection: () => LocalizedString
		/**
		 * Page layout and skin elements
		 */
		LayoutFeatures: () => LocalizedString
	}
	ImportSection: {
		/**
		 * Open geospatial file...
		 */
		OpenGeospatialFile: () => LocalizedString
		/**
		 * Open tabular file...
		 */
		OpenTabularFile: () => LocalizedString
		/**
		 * Example datasets
		 */
		ExampleDatasets: () => LocalizedString
	}
	MapConfiguration: {
		/**
		 * Dimensions
		 */
		Dimensions: () => LocalizedString
		/**
		 * Width
		 */
		Width: () => LocalizedString
		/**
		 * Height
		 */
		Height: () => LocalizedString
		/**
		 * Projection
		 */
		Projection: () => LocalizedString
		/**
		 * More projections
		 */
		MoreProjection: () => LocalizedString
		/**
		 * Custom projection...
		 */
		CustomProjection: () => LocalizedString
		/**
		 * Lock zoom / position
		 */
		LockZoom: () => LocalizedString
	}
	LayoutFeatures: {
		/**
		 * Background color
		 */
		BackgroundColor: () => LocalizedString
		/**
		 * Opacity
		 */
		Opacity: () => LocalizedString
		/**
		 * Map skin elements
		 */
		MapSkinElements: () => LocalizedString
		/**
		 * Sphere
		 */
		Sphere: () => LocalizedString
		/**
		 * Graticule
		 */
		Graticule: () => LocalizedString
		/**
		 * Rectangle
		 */
		Rectangle: () => LocalizedString
		/**
		 * Ellipse
		 */
		Ellipse: () => LocalizedString
		/**
		 * Line / Arrow
		 */
		Line: () => LocalizedString
		/**
		 * Text
		 */
		Text: () => LocalizedString
		/**
		 * Image
		 */
		Image: () => LocalizedString
		/**
		 * Scale bar
		 */
		ScaleBar: () => LocalizedString
		/**
		 * North arrow
		 */
		NorthArrow: () => LocalizedString
		/**
		 * Free drawing
		 */
		FreeDrawing: () => LocalizedString
		ContextMenu: {
			/**
			 * Edit
			 */
			Edit: () => LocalizedString
			/**
			 * Delete
			 */
			Delete: () => LocalizedString
			/**
			 * Up
			 */
			Up: () => LocalizedString
			/**
			 * Down
			 */
			Down: () => LocalizedString
		}
		DrawingInstructions: {
			/**
			 * Click to start drawing a line. Click again to add a point. Double-click to finish.
			 */
			Line: () => LocalizedString
		}
		Modal: {
			/**
			 * Settings
			 */
			Title: () => LocalizedString
			/**
			 * Fill color
			 */
			FillColor: () => LocalizedString
			/**
			 * Fill opacity
			 */
			FillOpacity: () => LocalizedString
			/**
			 * Stroke color
			 */
			StrokeColor: () => LocalizedString
			/**
			 * Stroke width
			 */
			StrokeWidth: () => LocalizedString
			/**
			 * Stroke opacity
			 */
			StrokeOpacity: () => LocalizedString
			/**
			 * Round corners
			 */
			RoundCorners: () => LocalizedString
			/**
			 * Rotation
			 */
			Rotation: () => LocalizedString
			/**
			 * X radius
			 */
			Rx: () => LocalizedString
			/**
			 * Y radius
			 */
			Ry: () => LocalizedString
			/**
			 * Width
			 */
			Width: () => LocalizedString
			/**
			 * Height
			 */
			Height: () => LocalizedString
			/**
			 * Distance unit
			 */
			Units: () => LocalizedString
			/**
			 * Meters
			 */
			m: () => LocalizedString
			/**
			 * Kilometers
			 */
			km: () => LocalizedString
			/**
			 * Miles
			 */
			mi: () => LocalizedString
			/**
			 * Feet
			 */
			ft: () => LocalizedString
			/**
			 * Yards
			 */
			yd: () => LocalizedString
			/**
			 * Nautical miles
			 */
			nmi: () => LocalizedString
			/**
			 * Scale bar type
			 */
			ScaleBarType: () => LocalizedString
			/**
			 * Simple line
			 */
			simpleLine: () => LocalizedString
			/**
			 * Line with ticks on top
			 */
			lineWithTicksOnTop: () => LocalizedString
			/**
			 * Line with ticks on bottom
			 */
			lineWithTicksOnBottom: () => LocalizedString
			/**
			 * Black and white bar
			 */
			blackAndWhiteBar: () => LocalizedString
			/**
			 * Tick values (comma separated, starting from 0)
			 */
			TickValues: () => LocalizedString
		}
	}
	AboutPanel: {
		/**
		 * About Magrit
		 */
		title: () => LocalizedString
		/**
		 * Magrit is an open source Web application for the visualization and the analysis of geospatial data. It is developed by the UAR RIATE (CNRS, Université Paris Cité).
		 */
		description: () => LocalizedString
		/**
		 * Useful links:
		 */
		usefulLinks: () => LocalizedString
		/**
		 * UAR RIATE
		 */
		UarRiate: () => LocalizedString
		/**
		 * GitHub project page
		 */
		linkGithub: () => LocalizedString
		/**
		 * GitHub issues
		 */
		linkGithubIssues: () => LocalizedString
		/**
		 * Documentation
		 */
		documentation: () => LocalizedString
	}
	LayerManager: {
		/**
		 * Point layer
		 */
		point: () => LocalizedString
		/**
		 * Line layer
		 */
		linestring: () => LocalizedString
		/**
		 * Polygon layer
		 */
		polygon: () => LocalizedString
		/**
		 * Raster layer
		 */
		raster: () => LocalizedString
		/**
		 * Data table
		 */
		table: () => LocalizedString
		/**
		 * Remove layer
		 */
		Delete: () => LocalizedString
		/**
		 * Attribute table
		 */
		AttributeTable: () => LocalizedString
		/**
		 * Zoom on layer
		 */
		FitZoom: () => LocalizedString
		/**
		 * Toggle visibility
		 */
		ToggleVisibility: () => LocalizedString
		/**
		 * Settings
		 */
		Settings: () => LocalizedString
		/**
		 * Fields typing
		 */
		Typing: () => LocalizedString
		/**
		 * Display / hide legend
		 */
		Legend: () => LocalizedString
		/**
		 * The position of the legend has been changed to reposition it in the map display area.
		 */
		LegendDisplacement: () => LocalizedString
	}
	PortrayalSection: {
		PortrayalTypes: {
			/**
			 * Choropleth
			 */
			Choropleth: () => LocalizedString
			/**
			 * Proportional symbols
			 */
			ProportionalSymbols: () => LocalizedString
			/**
			 * Labels
			 */
			Labels: () => LocalizedString
			/**
			 * Discontinuity
			 */
			Discontinuity: () => LocalizedString
			/**
			 * Categorical choropleth
			 */
			Categorical: () => LocalizedString
			/**
			 * Smoothed map
			 */
			Smoothed: () => LocalizedString
			/**
			 * No portrayal for the selected layer - Please verify the typing of the fields or select another layer
			 */
			NoPortrayal: () => LocalizedString
		}
		/**
		 * Representation choice
		 */
		RepresentationChoice: () => LocalizedString
		/**
		 * Target layer
		 */
		TargetLayer: () => LocalizedString
		/**
		 * Create layer
		 */
		CreateLayer: () => LocalizedString
		/**
		 * Result name
		 */
		ResultName: () => LocalizedString
		/**
		 * Type the name of the layer to create
		 */
		ResultNamePlaceholder: () => LocalizedString
		/**
		 * New_layer
		 */
		NewLayer: () => LocalizedString
		CommonOptions: {
			/**
			 * Variable
			 */
			Variable: () => LocalizedString
			/**
			 * Color
			 */
			Color: () => LocalizedString
		}
		ChoroplethOptions: {
			/**
			 * Choropleth
			 */
			Choropleth: () => LocalizedString
			/**
			 * Classification
			 */
			Classification: () => LocalizedString
			/**
			 * Color scheme
			 */
			ColorScheme: () => LocalizedString
			/**
			 * Invert color scheme
			 */
			ColorSchemeInvert: () => LocalizedString
			/**
			 * {{One class|?? classes}}
			 */
			CurrentNumberOfClasses: (arg0: number | string | boolean) => LocalizedString
		}
		ProportionalSymbolsOptions: {
			/**
			 * Reference size (px)
			 */
			ReferenceSize: () => LocalizedString
			/**
			 * On value
			 */
			OnValue: () => LocalizedString
			/**
			 * Symbol type
			 */
			SymbolType: () => LocalizedString
			SymbolTypes: {
				/**
				 * Circle
				 */
				circle: () => LocalizedString
				/**
				 * Square
				 */
				square: () => LocalizedString
				/**
				 * Line
				 */
				line: () => LocalizedString
			}
			/**
			 * Avoid overlapping symbols
			 */
			AvoidOverlapping: () => LocalizedString
			/**
			 * One color
			 */
			SingleColor: () => LocalizedString
			/**
			 * Two colors
			 */
			TwoColor: () => LocalizedString
			/**
			 * Limit value
			 */
			LimitValue: () => LocalizedString
		}
		DiscontinuityOptions: {
			/**
			 * Discontinuity type
			 */
			DiscontinuityType: () => LocalizedString
			/**
			 * Relative
			 */
			Relative: () => LocalizedString
			/**
			 * Absolute
			 */
			Absolute: () => LocalizedString
			/**
			 * Classification type
			 */
			Classification: () => LocalizedString
			/**
			 * Threshold of discontinuity to display
			 */
			DiscontinuityThreshold: () => LocalizedString
		}
		SmoothingOptions: {
			/**
			 * Smoothing type
			 */
			Type: () => LocalizedString
			/**
			 * Stewart's potential
			 */
			Stewart: () => LocalizedString
			/**
			 * Kernel density estimation
			 */
			KDE: () => LocalizedString
			/**
			 * Bandwidth
			 */
			Bandwidth: () => LocalizedString
			/**
			 * Kernel type
			 */
			KernelType: () => LocalizedString
			/**
			 * Pareto
			 */
			Pareto: () => LocalizedString
			/**
			 * Gaussian
			 */
			Gaussian: () => LocalizedString
			/**
			 * Epanechnikov
			 */
			Epanechnikov: () => LocalizedString
			/**
			 * Quartic
			 */
			Quartic: () => LocalizedString
			/**
			 * Triangular
			 */
			Triangular: () => LocalizedString
			/**
			 * Uniform
			 */
			Uniform: () => LocalizedString
			/**
			 * Span
			 */
			Span: () => LocalizedString
			/**
			 * Alpha
			 */
			Alpha: () => LocalizedString
			/**
			 * Beta
			 */
			Beta: () => LocalizedString
		}
	}
	ExportSection: {
		/**
		 * Select a layer
		 */
		SelectLayers: () => LocalizedString
		/**
		 * Select a format
		 */
		SelectFormat: () => LocalizedString
		/**
		 * Select a CRS
		 */
		SelectCRS: () => LocalizedString
		/**
		 * Layers
		 */
		Layers: () => LocalizedString
		/**
		 * Export
		 */
		Export: () => LocalizedString
		/**
		 * Export as PNG
		 */
		ExportPng: () => LocalizedString
		/**
		 * Export as SVG
		 */
		ExportSvg: () => LocalizedString
		/**
		 * Custom CRS
		 */
		CustomCRS: () => LocalizedString
		/**
		 * Clip SVG to current extent
		 */
		ClipSvgCurrentExtent: () => LocalizedString
	}
	LayerSettings: {
		/**
		 * Layer settings
		 */
		LayerSettings: () => LocalizedString
		/**
		 * Name
		 */
		Name: () => LocalizedString
		/**
		 * Fill color
		 */
		FillColor: () => LocalizedString
		/**
		 * Stroke color
		 */
		StrokeColor: () => LocalizedString
		/**
		 * Fill opacity
		 */
		FillOpacity: () => LocalizedString
		/**
		 * Stroke opacity
		 */
		StrokeOpacity: () => LocalizedString
		/**
		 * Stroke width
		 */
		StrokeWidth: () => LocalizedString
		/**
		 * Point radius
		 */
		PointRadius: () => LocalizedString
		/**
		 * Aesthetic filter
		 */
		AestheticFilter: () => LocalizedString
		/**
		 * Add a shadow
		 */
		DropShadow: () => LocalizedString
		/**
		 * Blur
		 */
		Blur: () => LocalizedString
		/**
		 * Allow moving symbols
		 */
		AllowMovingSymbols: () => LocalizedString
		/**
		 * Change classification options
		 */
		ChangeClassification: () => LocalizedString
		/**
		 * Font family
		 */
		FontFamily: () => LocalizedString
		/**
		 * Font size
		 */
		FontSize: () => LocalizedString
		/**
		 * Text color
		 */
		TextColor: () => LocalizedString
		/**
		 * X offset
		 */
		XOffset: () => LocalizedString
		/**
		 * Y offset
		 */
		YOffset: () => LocalizedString
		/**
		 * Font style
		 */
		FontStyle: () => LocalizedString
		/**
		 * Font weight
		 */
		FontWeight: () => LocalizedString
		/**
		 * Buffer around text
		 */
		BufferAroundText: () => LocalizedString
		/**
		 * Buffer color
		 */
		BufferColor: () => LocalizedString
		/**
		 * Buffer width
		 */
		BufferWidth: () => LocalizedString
		/**
		 * Allow moving labels
		 */
		AllowMovingLabels: () => LocalizedString
	}
	ProjectionSelection: {
		/**
		 * Projection selection
		 */
		title: () => LocalizedString
		/**
		 * Enter an EPSG code or a projection name
		 */
		SearchProjection: () => LocalizedString
		/**
		 * {{One projection found|?? projections found}}
		 */
		NMatchingProjections: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Too many results, please refine your search.
		 */
		TooManyResults: () => LocalizedString
		/**
		 * Kind:
		 */
		Kind: () => LocalizedString
		/**
		 * Projected coordinate reference system
		 */
		ProjCRS: () => LocalizedString
		/**
		 * Geographic coordinate reference system
		 */
		GeogCRS: () => LocalizedString
		/**
		 * Bounding box (geographic coordinates):
		 */
		BboxGeo: () => LocalizedString
		/**
		 * Bounding box (projected coordinates):
		 */
		BboxProjected: () => LocalizedString
		/**
		 * Area:
		 */
		Area: () => LocalizedString
		/**
		 * Unit:
		 */
		Unit: () => LocalizedString
		/**
		 * More information
		 */
		MoreInformation: () => LocalizedString
	}
	DataTable: {
		/**
		 * Attribute table
		 */
		titleGeo: () => LocalizedString
		/**
		 * Data table
		 */
		titleTabular: () => LocalizedString
		/**
		 * {{One feature|?? features}}
		 */
		Features: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{One column|?? columns}}
		 */
		Columns: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Export as CSV...
		 */
		ExportCsv: () => LocalizedString
		/**
		 * New column...
		 */
		NewColumn: () => LocalizedString
		/**
		 * Delete column
		 */
		DeleteColumn: () => LocalizedString
		NewColumnModal: {
			/**
			 * Back to data table
			 */
			BackToDatatable: () => LocalizedString
			/**
			 * New column
			 */
			title: () => LocalizedString
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Type the name of the column
			 */
			namePlaceholder: () => LocalizedString
			/**
			 * New column type
			 */
			newColumnType: () => LocalizedString
			/**
			 * Formula
			 */
			formula: () => LocalizedString
			/**
			 * Compute
			 */
			compute: () => LocalizedString
			/**
			 * Sample output
			 */
			sampleOutput: () => LocalizedString
			/**
			 * Error while parsing the formula
			 */
			errorParsingFormula: () => LocalizedString
			/**
			 * Error - empty result
			 */
			errorEmptyResult: () => LocalizedString
			/**
			 * Note that column names containing special characters or spaces must be enclosed in backticks or in brackets.
			 */
			noteSpecialCharacters: () => LocalizedString
			/**
			 * Division
			 */
			'/': () => LocalizedString
			/**
			 * Addition
			 */
			'+': () => LocalizedString
			/**
			 * Subtraction
			 */
			'-': () => LocalizedString
			/**
			 * Multiplication
			 */
			'*': () => LocalizedString
			/**
			 * Power operator
			 */
			'POWER()': () => LocalizedString
			/**
			 * Concatenate 2 or more strings
			 */
			'CONCAT()': () => LocalizedString
			/**
			 * Extract a substring
			 */
			'SUBSTRING()': () => LocalizedString
			/**
			 * Special field - The length of the dataset (number of features)
			 */
			specialFieldLength: () => LocalizedString
			/**
			 * Special field - The area of the feature, in square meters (only for polygon layers). Note that this calculation is based on the geographical coordinates and is made on the spheroid. This result may be less accurate than if the calculation had been carried out in a local projection based on an adapted ellipsoid.
			 */
			specialFieldArea: () => LocalizedString
			/**
			 * Special field - The (internal) row id of the feature
			 */
			specialFieldId: () => LocalizedString
		}
	}
	FieldsTyping: {
		/**
		 * Fields typing
		 */
		ModalTitle: () => LocalizedString
		/**
		 * Field name
		 */
		FieldName: () => LocalizedString
		/**
		 * Field type
		 */
		FieldType: () => LocalizedString
		VariableTypes: {
			/**
			 * Identifier
			 */
			identifier: () => LocalizedString
			/**
			 * Ratio
			 */
			ratio: () => LocalizedString
			/**
			 * Stock
			 */
			stock: () => LocalizedString
			/**
			 * Categorical
			 */
			categorical: () => LocalizedString
			/**
			 * Unknown
			 */
			unknown: () => LocalizedString
		}
	}
	ClassificationPanel: {
		/**
		 * Classification
		 */
		title: () => LocalizedString
		/**
		 * Box
		 */
		box: () => LocalizedString
		/**
		 * Histogram
		 */
		histogram: () => LocalizedString
		/**
		 * Beeswarm
		 */
		beeswarm: () => LocalizedString
		/**
		 * Dot histogram
		 */
		dotHistogram: () => LocalizedString
		/**
		 * Histogram and density
		 */
		histogramAndDensity: () => LocalizedString
		/**
		 * Values distribution
		 */
		distribution: () => LocalizedString
		/**
		 * Summary
		 */
		summary: () => LocalizedString
		/**
		 * Population (non-null values)
		 */
		population: () => LocalizedString
		/**
		 * Minimum
		 */
		minimum: () => LocalizedString
		/**
		 * Maximum
		 */
		maximum: () => LocalizedString
		/**
		 * Mean
		 */
		mean: () => LocalizedString
		/**
		 * Median
		 */
		median: () => LocalizedString
		/**
		 * Standard deviation
		 */
		standardDeviation: () => LocalizedString
		/**
		 * Variance
		 */
		variance: () => LocalizedString
		/**
		 * Variance coefficient
		 */
		varianceCoefficient: () => LocalizedString
		/**
		 * Skewness
		 */
		skewness: () => LocalizedString
		/**
		 * Classification
		 */
		classification: () => LocalizedString
		/**
		 * Classification method
		 */
		classificationMethod: () => LocalizedString
		classificationMethods: {
			/**
			 * Equal intervals
			 */
			equalIntervals: () => LocalizedString
			/**
			 * Quantiles
			 */
			quantiles: () => LocalizedString
			/**
			 * Jenks
			 */
			jenks: () => LocalizedString
			/**
			 * Standard deviation
			 */
			standardDeviation: () => LocalizedString
			/**
			 * Q6
			 */
			q6: () => LocalizedString
			/**
			 * Pretty
			 */
			pretty: () => LocalizedString
			/**
			 * Geometric progression
			 */
			geometricProgression: () => LocalizedString
			/**
			 * Arithmetic progression
			 */
			arithmeticProgression: () => LocalizedString
			/**
			 * Head/tail
			 */
			headTail: () => LocalizedString
			/**
			 * Manual
			 */
			manual: () => LocalizedString
		}
		classificationMethodLegendDescriptions: {
			/**
			 * Classified using equal intervals
			 */
			equalIntervals: () => LocalizedString
			/**
			 * Classified using quantiles
			 */
			quantiles: () => LocalizedString
			/**
			 * Classified using natural breaks (Jenks)
			 */
			jenks: () => LocalizedString
			/**
			 * Classified using mean and standard deviation
			 */
			standardDeviation: () => LocalizedString
			/**
			 * Classified using the Q6 method
			 */
			q6: () => LocalizedString
			/**
			 * Classified using the "pretty breaks" method
			 */
			pretty: () => LocalizedString
			/**
			 * Classified using a geometric progression
			 */
			geometricProgression: () => LocalizedString
			/**
			 * Classified using an arithmetic progression
			 */
			arithmeticProgression: () => LocalizedString
			/**
			 * Classified using the head/tail break method
			 */
			headTail: () => LocalizedString
			/**
			 * Classified manually
			 */
			manual: () => LocalizedString
		}
		/**
		 * Number of classes
		 */
		numberOfClasses: () => LocalizedString
		/**
		 * Mean value position
		 */
		meanPosition: () => LocalizedString
		/**
		 * Class center
		 */
		meanPositionCenter: () => LocalizedString
		/**
		 * Class boundary
		 */
		meanPositionBoundary: () => LocalizedString
		/**
		 * Amplitude
		 */
		amplitude: () => LocalizedString
		/**
		 * standard deviations
		 */
		howManyStdDev: () => LocalizedString
		/**
		 * Palette
		 */
		palette: () => LocalizedString
		/**
		 * Reverse palette
		 */
		reversePalette: () => LocalizedString
		/**
		 * Display mean
		 */
		displayMean: () => LocalizedString
		/**
		 * Display median
		 */
		displayMedian: () => LocalizedString
		/**
		 * Display standard deviation
		 */
		displayStdDev: () => LocalizedString
		/**
		 * Logarithmic scale
		 */
		logarithmicScale: () => LocalizedString
		/**
		 * Enter class limits
		 */
		breaksInput: () => LocalizedString
		/**
		 * Validate
		 */
		validate: () => LocalizedString
		/**
		 * {{One feature without data|?? feature without data}}
		 */
		missingValues: (arg0: number | string | boolean) => LocalizedString
		/**
		 * Features per class
		 */
		count: () => LocalizedString
	}
	Legend: {
		ContextMenu: {
			/**
			 * Edit
			 */
			Edit: () => LocalizedString
			/**
			 * Hide
			 */
			Hide: () => LocalizedString
			/**
			 * Up
			 */
			Up: () => LocalizedString
			/**
			 * Down
			 */
			Down: () => LocalizedString
		}
		Modal: {
			/**
			 * Legend settings
			 */
			Title: () => LocalizedString
			/**
			 * Legend title
			 */
			LegendTitle: () => LocalizedString
			/**
			 * Legend subtitle
			 */
			LegendSubtitle: () => LocalizedString
			/**
			 * Legend note
			 */
			LegendNote: () => LocalizedString
			/**
			 * Display a rectangle under the legend
			 */
			DisplayBackgroundRectangle: () => LocalizedString
			/**
			 * Background rectangle color
			 */
			BackgroundRectangleColor: () => LocalizedString
			/**
			 * Background rectangle fill opacity
			 */
			BackgroundRectangleOpacity: () => LocalizedString
			/**
			 * Background rectangle stroke color
			 */
			BackgroundRectangleStrokeColor: () => LocalizedString
			/**
			 * Background rectangle stroke width
			 */
			BackgroundRectangleStrokeWidth: () => LocalizedString
			/**
			 * Background rectangle stroke opacity
			 */
			BackgroundRectangleStrokeOpacity: () => LocalizedString
			/**
			 * Legend orientation
			 */
			LegendOrientation: () => LocalizedString
			/**
			 * Horizontal
			 */
			LegendOrientationHorizontal: () => LocalizedString
			/**
			 * Vertical
			 */
			LegendOrientationVertical: () => LocalizedString
			/**
			 * Legend layout
			 */
			LegendSymbolLayout: () => LocalizedString
			/**
			 * Vertical
			 */
			LegendSymbolLayoutVertical: () => LocalizedString
			/**
			 * Horizontal
			 */
			LegendSymbolLayoutHorizontal: () => LocalizedString
			/**
			 * Stacked
			 */
			LegendSymbolLayoutStacked: () => LocalizedString
			/**
			 * Box width
			 */
			BoxWidth: () => LocalizedString
			/**
			 * Box height
			 */
			BoxHeight: () => LocalizedString
			/**
			 * Spacing between boxes
			 */
			BoxSpacing: () => LocalizedString
			/**
			 * Spacing between boxes and no data box
			 */
			BoxSpacingNoData: () => LocalizedString
			/**
			 * Label for the "no data" box
			 */
			NoDataLabel: () => LocalizedString
			/**
			 * Box corner radius
			 */
			BoxCornerRadius: () => LocalizedString
			/**
			 * Box stroke width
			 */
			BoxStrokeWidth: () => LocalizedString
			/**
			 * Round values
			 */
			RoundDecimals: () => LocalizedString
			/**
			 * More options...
			 */
			MoreOptions: () => LocalizedString
			/**
			 * Spacing between symbols
			 */
			SymbolsSpacing: () => LocalizedString
			/**
			 * Choice of values
			 */
			ChooseValues: () => LocalizedString
			/**
			 * Line length
			 */
			LineLength: () => LocalizedString
		}
	}
	CommonTextElement: {
		/**
		 * Font size
		 */
		FontSize: () => LocalizedString
		/**
		 * Font color
		 */
		FontColor: () => LocalizedString
		/**
		 * Font family
		 */
		FontFamily: () => LocalizedString
		/**
		 * Font weight
		 */
		FontWeight: () => LocalizedString
		/**
		 * Font style
		 */
		FontStyle: () => LocalizedString
		/**
		 * Normal
		 */
		Normal: () => LocalizedString
		/**
		 * Bold
		 */
		Bold: () => LocalizedString
		/**
		 * Italic
		 */
		Italic: () => LocalizedString
		/**
		 * Underline
		 */
		Underline: () => LocalizedString
	}
}

export type Formatters = {}
